import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import StoreProvider from '@/hooks/StoreProvider';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <StoreProvider>
        <main>
          {children}
        </main>
      </StoreProvider>

      <Toaster duration={2000} position={'top-right'} />

      </body>
      </html>
  );
}
